import classNames from 'classnames';
import ThreeDotsWave from '~/components/animation/three-dots-wave';
import { useTranslate } from '~/i18n';
import { ArrowRightIcon } from '@heroicons/react/20/solid';
import React from 'react';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
type SubmitBtnProps = {
   loading?: boolean;
   text: string;
   id: string;
   className?: string;
   noIcon?: boolean;
   icon?: React.ReactNode;
   secondary?: boolean;
   disable?: boolean;
   customLoader?: React.ReactNode;
};

const SubmitBtn = ({
   className,
   loading,
   text,
   id,
   icon,
   secondary,
   noIcon = false,
   disable,
   customLoader,
}: SubmitBtnProps) => {
   const { lang } = useTranslate();
   return (
      <button
         disabled={disable || loading}
         type="submit"
         id={id}
         className={classNames(
            className,
            'block w-full  rounded-none border-none border-transparent px-4 py-3 text-center text-sm font-medium leading-5 text-white transition-colors duration-150  focus:outline-none focus:ring  focus:ring-opacity-50  ',
            (loading || disable) && 'disabled:cursor-not-allowed disabled:opacity-50 ',
            secondary
               ? 'bg-secondary enabled:hover:bg-secondary-600 focus:ring-opacity-50 enabled:focus:ring-light-green enabled:active:bg-light-green-600'
               : 'bg-light-green focus:ring-opacity-50 enabled:focus:ring-light-green enabled:active:bg-light-green-600',
            ''
         )}>
         {noIcon ? (
            <span className="inline-flex">
               <div className={classNames('my-auto')}>
                  {loading ? (
                     <div className="w-8">
                        {customLoader ? customLoader : <ThreeDotsWave color="white" />}
                     </div>
                  ) : (
                     <div className="my-auto">{text}</div>
                  )}
               </div>
            </span>
         ) : (
            <span className="inline-flex">
               <div className="my-auto">{text}</div>
               <div className={classNames('my-auto ltr:ml-2 rtl:mr-2', lang === 'ar' && 'flip-x')}>
                  {loading ? (
                     <div className="w-8">
                        {customLoader ? customLoader : <ThreeDotsWave color="white" />}
                     </div>
                  ) : (
                     <React.Fragment>
                        {icon ? icon : <ArrowRightIcon className="h-5 w-5" />}
                     </React.Fragment>
                  )}
               </div>
            </span>
         )}
      </button>
   );
};

export default SubmitBtn;
