import React from 'react';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const Favicon = () => {
   return (
      <React.Fragment>
         <meta name="apple-mobile-web-app-capable" content="yes" />
         <meta name="apple-mobile-web-app-status-bar-style" content="default" />
         <meta name="apple-mobile-web-app-title" content="Lucky Draw" />
         {/* //todo: to check */}
         <meta name="format-detection" content="telephone=no" />
         <meta name="mobile-web-app-capable" content="yes" />
         {/* theme-color */}
         <meta name="theme-color" content="#e72906" />

         {/* <!-- favicon sizes --> */}
         <link rel="shortcut icon" href={`${process.env.NEXT_PUBLIC_BASE_URL}/favicon.ico`} />
         <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
         <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
         <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
         <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
         <meta name="msapplication-TileColor" content="#da532c" />

         {/* manifest */}
         {/* <link rel="manifest" href="/manifest.json" /> */}
      </React.Fragment>
   );
};

export default Favicon;
