// import { Translate, useTranslate } from '~/i18n';
// import { motion } from 'framer-motion';
import classNames from 'classnames';
import React from 'react';
import { NextLink, Translate } from '~/i18n';
import Image from '../shared/image';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const HomepageSections = () => {
   return (
      <section>
         <div className="container lg:py-20">
            <div className="row">
               <div className="col-12 mx-auto pt-20  text-center">
                  <div className="relative ">
                     <div>
                        <div className="mx-auto h-[130px] w-[290px] md:h-[200px] md:w-[440px]">
                           <Image
                              src="/images/zatca.png"
                              alt="zatca logo"
                              // width="150"
                              // height="71"
                              layout="fill"
                              objectFit="contain"
                              className=""
                           />
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div className="row pt-10 text-center">
               <div className="mb-4 md:col-4">
                  <NextLink
                     href={`/draw/${1}`}
                     className={classNames(
                        'block rounded-md border border-white px-2 py-2 font-semibold text-white transition-colors duration-150  rtl:justify-end',
                        'focus:border-white focus:outline-none focus:ring focus:ring-white focus:ring-opacity-50 '
                     )}>
                     <Translate id="web:draw_1_winner" />
                  </NextLink>
               </div>
               <div className="mb-4 md:col-4">
                  <NextLink
                     href={`/draw/${3}`}
                     className={classNames(
                        'block rounded-md border border-white px-2 py-2 font-semibold text-white transition-colors duration-150  rtl:justify-end',
                        'focus:border-white focus:outline-none focus:ring focus:ring-white focus:ring-opacity-50 '
                     )}>
                     <Translate id="web:draw_3_winner" />
                  </NextLink>
               </div>
               <div className="mb-4 md:col-4">
                  <NextLink
                     href={`/draw/${10}`}
                     className={classNames(
                        'block rounded-md border border-white px-2 py-2 font-semibold text-white transition-colors duration-150  rtl:justify-end',
                        'focus:border-white focus:outline-none focus:ring focus:ring-white focus:ring-opacity-50 '
                     )}>
                     <Translate id="web:draw_10_winner" />
                  </NextLink>
               </div>
            </div>
         </div>
      </section>
   );
};

export default HomepageSections;
