import { motion } from 'framer-motion';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
type ThreeDotsWaveProps = {
   color: string;
};
const ThreeDotsWave = ({ color }: ThreeDotsWaveProps) => {
   const loadingContainer = {
      height: '1rem',
      display: 'flex',
      justifyContent: 'space-around',
   };

   const loadingCircle = {
      display: 'block',
      width: '0.3rem',
      height: '0.3rem',
      backgroundColor: color || 'white',
      borderRadius: '12px',
   };

   const loadingContainerVariants = {
      start: {
         transition: {
            staggerChildren: 0.2,
         },
      },
      end: {
         transition: {
            staggerChildren: 0.2,
         },
      },
   };

   const loadingCircleVariants = {
      start: {
         y: '50%',
      },
      end: {
         y: '150%',
      },
   };

   const loadingCircleTransition = {
      duration: 0.5,
      repeat: Infinity,
      ease: 'easeInOut',
   };
   return (
      <motion.div
         style={loadingContainer}
         variants={loadingContainerVariants}
         initial="start"
         animate="end">
         <motion.span
            style={loadingCircle}
            variants={loadingCircleVariants}
            transition={loadingCircleTransition}
         />
         <motion.span
            style={loadingCircle}
            variants={loadingCircleVariants}
            transition={loadingCircleTransition}
         />
         <motion.span
            style={loadingCircle}
            variants={loadingCircleVariants}
            transition={loadingCircleTransition}
         />
      </motion.div>
   );
};

export default ThreeDotsWave;
